GeorgeCimpoeru/backend_repo

rest_api/actions/base_actions.py, rest_api/actions/dtc_info.py, rest_api/actions/generate_frames.py, rest_api/routes/api.py
- Updated the read_dtc function to correctly format JSON for the report_dtcs subfunction and fixed the bug causing the 'nonetype object cannot be interpreted as an integer' error when subfunction 2 was called without reading any DTCs.
- Added support for the clear_dtc_info endpoint to accept a DTC group as a parameter for clearing.
=> Read DTC and Clear DTC endpoint fixed

mcu/src/ReceiveFrames.cpp, rest_api/actions/access_timing_action.py, rest_api/actions/generate_frames.py, rest_api/routes/api.py, uds/access_timing_parameters/src/AccessTimingParameter.cpp, utils/src/ReceiveFrames.cpp
-Updated the read and write endpoints to accept the ECU ID in the JSON payload for specifying the target ECU for operations. Added the sub_function parameter to the write endpoint to indicate whether to perform a reset or write on access timing parameters. 
-Modified the backend logic so that the accessTimingParameters values are stored in milliseconds.
=> Read&Write Access Timing Parameters endpoint improve

rest_api/actions/generate_frames.py, rest_api/actions/update_action.py, rest_api/routes/api.py, rest_api/tests/mocking_tests_reads.py, rest_api/tests/mocking_tests_writes.py, rest_api/utils/curls.txt
API OTA STATUS UPDATE. POST API that execute a specific hex value relying on a specific dictionary
Mocking tests for API routes writes/reads. They are started but they are not finished yet.
=> Api ota_status route + mocking tests read/write

rest_api/actions/dtc_info.py, uds/access_timing_parameters/src/AccessTimingParameter.cpp, uds/clear_dtc/src/ClearDtc.cpp, utils/include/GenerateFrames.h, utils/src/GenerateFrames.cpp, utils/src/ReceiveFrames.cpp
-Updated the ClearDtc service in the backend to return the number of cleared DTCs when the result is positive. Included this information in the JSON sent from the API, along with the group used to filter the DTCs.
-Added logic to join the thread even in cases of a positive response.
=> ClearDTC json return modified and bug fixed.

rest_api/actions/read_info_action.py, rest_api/actions/write_info_action.py, rest_api/configs/data_identifiers.py
-state_of_charge replaced with battery_state_of_charge in API
=> state_of_charge replaced with battery_state_of_charge

mcu/include/ReceiveFrames.h, mcu/src/ReceiveFrames.cpp, uds/access_timing_parameters/src/AccessTimingParameter.cpp, utils/include/ReceiveFrames.h, utils/src/ReceiveFrames.cpp
- Correctly setting the Response-Pending frame ID.
- Fixed the bug where the process would hang after sending a Response-Pending frame.
=> Bad response with 3100 bug fixed

ecu_simulation/BatteryModule/Makefile, ecu_simulation/BatteryModule/src/BatteryModule.cpp, ecu_simulation/DoorsModule/Makefile, ecu_simulation/DoorsModule/src/DoorsModule.cpp, ecu_simulation/EngineModule/Makefile, ecu_simulation/EngineModule/src/EngineModule.cpp, ecu_simulation/HVACModule/Makefile, ecu_simulation/HVACModule/src/HVACModule.cpp, mcu/Makefile, mcu/src/MCUModule.cpp, rest_api/actions/diag_session.py, rest_api/actions/request_id_action.py, rest_api/actions/update_action.py, rest_api/configs/data_identifiers.py, uds/routine_control/src/RoutineControl.cpp
- Synced the SOFTWARE_VERSION flag with the memory area on the dev loop that stores the program's software version.
- Updated the request_ids endpoint to include the MCU software version in the response.
- Enhanced the /update_to_version endpoint to verify that the target update version is not already running on the ECU/MCU.
- Send a positive response in the backend before updating a module.
=> Improved OTA functionality: added version check, version sync and update endpoints

.gitignore, config/Makefile, config/config.ini, config/generate_config.py, ecu_simulation/BatteryModule/Makefile, ecu_simulation/DoorsModule/Makefile, ecu_simulation/EngineModule/Makefile, ecu_simulation/HVACModule/Makefile, mcu/Makefile
This MR updates .gitignore to exclude generated binaries logs and result files to prevent unnecessary tracking it also adds an automated generation of config.ini in the Makefile eliminating the need for manual tracking and updates dependent Makefiles to ensure config.ini is correctly triggered during the build .
=> Improve .gitignore and Automate config.ini Generation

.github/workflows/build_checker.yml
Github actions v3 is deprecated, leading to pipeline failures. The aim of this fix is to upgrade to v4 to prevent hiding failures caused by our errors
=> chore: upgrade actions from v3 to v4

uds/read_data_by_identifier/src/ReadDataByIdentifier.cpp
This MR introduces a call to fetchBatteryData("r") in readDataByIdentifier to ensure battery data is always up to date before being read.
⚠️ Note: Failures related to pipes build are caused by the latest update from GitHub
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Ensure battery data is updated before reading

ecu_simulation/BatteryModule/src/BatteryModule.cpp
Root of the issue of battery percentage being displayed as 1 instead of 100 laid in the parsing of battery data inside the battery module. After splitting the digits of the decimal value of the percentage in groups of 2, the decimal_value variable would actually store 1 instead of 100. In order to fix this issue, I simplified the code for converting the battery percentage to a hex string by removing the extra percentage_grouped and decimal_value, working directly on percentage_value. I found it necessary to change the datatype of percentage_value from uint8_t to uint16_t as the percentage_value behaved as a char.
With my changes, I started the MCU, BatteryModule (I have the laptop battery at 100%), rest_api and frontend. In the UDS/Battery page, the battery percentage is 100%
=> Fix displayed battery value

ecu_simulation/BatteryModule/src/main.cpp, ecu_simulation/DoorsModule/Makefile, ecu_simulation/DoorsModule/src/main.cpp, ecu_simulation/EngineModule/src/main.cpp, ecu_simulation/HVACModule/src/main.cpp, mcu/include/MCUModule.h, mcu/src/MCUModule.cpp, mcu/src/main.cpp, utils/include/ECU.h, utils/src/ECU.cpp
- Added a function to each module that is called at the start of the program to terminate all processes running the current program's executable, except for the current process. This ensures orphaned processes left running in the background after an update_to_version are properly terminated.
=> Orphan process running in background fixed

ecu_simulation/BatteryModule/Makefile, ecu_simulation/DoorsModule/Makefile, ecu_simulation/EngineModule/Makefile, ecu_simulation/HVACModule/Makefile, mcu/Makefile
`make allTests` did not build the ECU modules tests. Additionally, when running `make clean` from either the MCU makefile or the makefile of any ECU, the test related files were not removed.
I added these module tests at allTests in the MCU makefile. All ECU test and coverage related files are removed in the MCU makefile (for all ECUs) and in their respective makefile (for each ECU).
Tested on branch feature/fixMakeAllTests2 as make allTests is currently failing on development
=> fix: make ECU tests in allTests and clean ECU test files in both MCU and ECUs makefiles

mcu/Makefile
Moving countDigits and to_lowercase from their respective classes to Globals caused several test executables to not build, as the Globals_test.o file was not linked to the executable.
⚠️ **Action requested**: Prioritize creating a CI job to build and run test executables
⚠️ Until we create a CI test job we should locally run `make allTests` to ensure this kind of errors do not occur again
make allTests works again
=> fix: add Globals test object file

ecu_simulation/BatteryModule/src/main.cpp, ecu_simulation/DoorsModule/src/main.cpp, ecu_simulation/EngineModule/src/main.cpp, ecu_simulation/HVACModule/src/main.cpp, mcu/Makefile, mcu/src/main.cpp, uds/ecu_reset/include/DummyEcuReset.h, uds/ecu_reset/include/EcuReset.h, uds/ecu_reset/src/DummyEcuReset.cpp, uds/ecu_reset/src/EcuReset.cpp, uds/ecu_reset/utest/EcuResetTest.cpp
The following uses of the UNIT_TESTING_MODE preprocessor directive were removed with my changes:
1. Selection of default or parametrized Logger constructor inside the main functions for MCU and ECUs -> this is redundant as the console logger is used anyway during testing; only the parametrized Logger constructor will be used
2. Performing no actual resets in EcuReset::hardReset if we are in testing mode -> extracted the testing behavior in a dummy class
The following uses of the UNIT_TESTING_MODE preprocessor directive were NOT removed with my changes:
1. Changing the initially set DiagnosticSession inside DiagnosticSessionControl -> I considered extracting sessionControl in a standalone function but it uses class internals; I considered removing the UNKNOWN_SESSION altogether due to …
=> Separate testing code from production code

ecu_simulation/BatteryModule/src/main.cpp, ecu_simulation/DoorsModule/src/main.cpp, ecu_simulation/EngineModule/src/main.cpp, ecu_simulation/HVACModule/src/main.cpp, mcu/src/main.cpp, mcu/test/MCUModuleTest.cpp, mcu/test/ReceiveFramesTest.cpp, utils/include/Globals.h, utils/src/Globals.cpp
Currently there are 2 loadProjectPath functions, one for MCU and one for ECU. They use paths relative to the current working directory, which may cause issues when running an executable from another directory other than the source file's path. This PR aims to use a single loadProjectPath that works irrespective of the current working directory by repeatedly looking in the current filepath if the last directory is "backend" and the appending to it "config/config.ini". The new implementation replaces loadProjectPathForMCU/ECU
Tested by running main_mcu and main_battery with my changes
=> refactor: rework loadProjectPath to be independent of current working directory

ota/request_transfer_exit/utest/RequestTransferExitTest.cpp
The following rework was done on the request transfer exit tests:
1. Loaded project path in test constructor, which fixed RequestTransferExitTest::RequestSequenceError
2. Removed obsolete test RequestTransferExitTest::OTAUpStDIDNotFound
3. Set OTA_UPDATE_STATUS_DID to PROCESSING_TRANSFER_COMPLETE inside RequestTransferExitTest::PositiveResponse
With my rework, all tests pass and coverage is 100%. See ticket for screenshots
=> test: rework request transfer exit tests

mcu/Makefile, mcu/src/MCUModule.cpp, uds/read_memory_by_address/include/ReadMemoryByAddress.h, uds/read_memory_by_address/src/ReadMemoryByAddress.cpp, uds/read_memory_by_address/utest/ReadMemoryByAddressTest.cpp, uds/routine_control/src/RoutineControl.cpp, utils/include/GenerateFrames.h, utils/include/IMemoryManager.h, utils/include/MemoryManager.h, utils/include/MockGenerateFrames.h, utils/include/MockMemoryManager.h, utils/include/TestUtils.h, utils/src/ECU.cpp, utils/src/TestUtils.cpp
The following changes are provided in this PR:
1. Implementation of a mock MemoryManager: In order to achieve this, I turned the readMemoryAddress static method into a member method. Along with availableAddress, availableMemory and getPath, these methods were extracted into a new IMemoryManager interface, extended by both MemoryManager and the newly created mock. This IMemoryManager interface replaces the MemoryManager in the ReadMemoryFromAddress' constructor. The aforementioned methods are used in the ReadMemoryByAddressUTs (see 4.), but the interface and the mock are open to adding new methods
2. Implementation of a mock GenerateFrames: the readMemoryByAddress and readMemoryByAddressLongResponse were made virtual, implemented in the mock, used in the ReadMemoryByAddressUTs (see 4.), …
=> Provide ReadMemoryByAddressUTs, mocks for memorymanager and generateframes, and include gmock in makefile

ecu_simulation/EngineModule/src/EngineModule.cpp, ecu_simulation/EngineModule/test/EngineModuleTest.cpp
EngineModuleTest::checkDTCCreateFileSuccessfully failed as it could not open the dtcs.txt file. This was because the project path was not yet loaded. Fixed by adding a call to loadProjectPath in the test suite constructor. Additionally, a new log is added for when we fail to open a file input stream to dtcs.txt. For coverage purpose, the path to engine_data and old_engine_data was updated to be dependant on the PROJECT_PATH
All tests pass and 100% coverage achieved
=> test: fix failing UT and add extra logging

ecu_simulation/BatteryModule/src/BatteryModule.cpp, ecu_simulation/BatteryModule/test/BatteryModuleTest.cpp
Loaded the project path in the test constructor. Changed the path towards battery_data.txt so that no additional empty file is created in test directory. For parseBatteryInfo unit test, string comparison was performed between a hex and a decimal but the effective value was the same. For simplicity, no hex conversion is done when reading from battery_data.txt
=> test: fix batteryModuleTests

ota/transfer_data/src/TransferData.cpp, ota/transfer_data/utest/TransferDataTest.cpp
The following changes are presented in this PR:
1. Refactored some printing statements to output a newline
2. WrongBlockSequenceNumberTest failed prematurely as the OTA state was not set to an expected value. In that regard, I renamed the current WrongBlockSequenceNumberTest to IncorrectOTAStateTest and redid WrongBlockSequenceNumberTest with a valid OTAState
3. The wrong frame was expected for the PositiveResponseTest; i changed it to the actual expected frame and, for coverage purposes, I added a call to getChecksums.
4. for both WrongBlockSequenceNumberTest and PositiveResponseTest I added a couple extra capture calls because the expected frame is not the first one sent
5. Added an unit test to cover the edge case when the expected block sequence number overflows the max uint8_t value …
=> test: provide TransferData UTs

mcu/Makefile
The creation of the config.ini file was limited to the all make target. This PR proposes the introduction of a new target, allPreProcess, which will create the config.ini (named allPreProcess in case any other tasks are to be added to this target). This target is built when making all, or any standalone test executable (used also by allTests, the run targets and the coverage targets).
The job was not deemed necessary for the clean tasks nor was it necessary to be added to the Ecu modules' makefiles.
I tested this change as follows:
1. To ensure how many times the allPreProcess job should appear in the makefile, I counted how many test targets there are in allTests (I also added the fileManagerTests which is currently missing but will be added when merging this PR: …
=> chore: add allPreProcess target
